services:
  service-email:
    image: service-email
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: dockerfile.dev
    networks:
      - local-net
networks:
  local-net:
    driver: bridge