FROM node:20-slim
WORKDIR /usr/src/app

ARG NODE_ENV=hom
ENV NODE_ENV=${NODE_ENV}
ENV DOTENV_CONFIG_PATH=.env.${NODE_ENV}

COPY . .
COPY .npmrc.build ./.npmrc

RUN npm install --loglevel verbose
RUN npm run build

CMD ["node", "-r", "dotenv/config", "dist/main.js"]